// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe
{
    [StripeResourceType("stripe:index/productFeature:ProductFeature")]
    public partial class ProductFeature : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the Entitlements Feature the product will be attached to
        /// </summary>
        [Output("entitlementsFeature")]
        public Output<string> EntitlementsFeature { get; private set; } = null!;

        /// <summary>
        /// Has the value true if the object exists in live mode or the value false if the object exists in test mode
        /// </summary>
        [Output("livemode")]
        public Output<bool> Livemode { get; private set; } = null!;

        /// <summary>
        /// String representing the object’s type. Objects of the same type share the same value.
        /// </summary>
        [Output("object")]
        public Output<string> Object { get; private set; } = null!;

        /// <summary>
        /// The ID of the product that this Entitlements Feature will be attached to.
        /// </summary>
        [Output("product")]
        public Output<string> Product { get; private set; } = null!;


        /// <summary>
        /// Create a ProductFeature resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProductFeature(string name, ProductFeatureArgs args, CustomResourceOptions? options = null)
            : base("stripe:index/productFeature:ProductFeature", name, args ?? new ProductFeatureArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProductFeature(string name, Input<string> id, ProductFeatureState? state = null, CustomResourceOptions? options = null)
            : base("stripe:index/productFeature:ProductFeature", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProductFeature resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProductFeature Get(string name, Input<string> id, ProductFeatureState? state = null, CustomResourceOptions? options = null)
        {
            return new ProductFeature(name, id, state, options);
        }
    }

    public sealed class ProductFeatureArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the Entitlements Feature the product will be attached to
        /// </summary>
        [Input("entitlementsFeature", required: true)]
        public Input<string> EntitlementsFeature { get; set; } = null!;

        /// <summary>
        /// The ID of the product that this Entitlements Feature will be attached to.
        /// </summary>
        [Input("product", required: true)]
        public Input<string> Product { get; set; } = null!;

        public ProductFeatureArgs()
        {
        }
        public static new ProductFeatureArgs Empty => new ProductFeatureArgs();
    }

    public sealed class ProductFeatureState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the Entitlements Feature the product will be attached to
        /// </summary>
        [Input("entitlementsFeature")]
        public Input<string>? EntitlementsFeature { get; set; }

        /// <summary>
        /// Has the value true if the object exists in live mode or the value false if the object exists in test mode
        /// </summary>
        [Input("livemode")]
        public Input<bool>? Livemode { get; set; }

        /// <summary>
        /// String representing the object’s type. Objects of the same type share the same value.
        /// </summary>
        [Input("object")]
        public Input<string>? Object { get; set; }

        /// <summary>
        /// The ID of the product that this Entitlements Feature will be attached to.
        /// </summary>
        [Input("product")]
        public Input<string>? Product { get; set; }

        public ProductFeatureState()
        {
        }
        public static new ProductFeatureState Empty => new ProductFeatureState();
    }
}
