// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe
{
    [StripeResourceType("stripe:index/shippingRate:ShippingRate")]
    public partial class ShippingRate : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether the shipping rate can be used for new purchases. Defaults to true.
        /// </summary>
        [Output("active")]
        public Output<bool?> Active { get; private set; } = null!;

        [Output("deliveryEstimates")]
        public Output<ImmutableArray<Outputs.ShippingRateDeliveryEstimate>> DeliveryEstimates { get; private set; } = null!;

        /// <summary>
        /// The name of the shipping rate, meant to be displayable to the customer. This will appear on CheckoutSessions.
        /// </summary>
        [Output("displayName")]
        public Output<string> DisplayName { get; private set; } = null!;

        /// <summary>
        /// Describes a fixed amount to charge for shipping. Must be present for now.
        /// </summary>
        [Output("fixedAmount")]
        public Output<Outputs.ShippingRateFixedAmount> FixedAmount { get; private set; } = null!;

        /// <summary>
        /// Has the value true if the object exists in live mode or the value false if the object exists in test mode.
        /// </summary>
        [Output("livemode")]
        public Output<bool> Livemode { get; private set; } = null!;

        /// <summary>
        /// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
        /// object in a structured format.
        /// </summary>
        [Output("metadata")]
        public Output<ImmutableDictionary<string, string>?> Metadata { get; private set; } = null!;

        /// <summary>
        /// Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or
        /// unspecified.
        /// </summary>
        [Output("taxBehavior")]
        public Output<string?> TaxBehavior { get; private set; } = null!;

        /// <summary>
        /// A tax code ID. The Shipping tax code is txcd_92010001.
        /// </summary>
        [Output("taxCode")]
        public Output<string?> TaxCode { get; private set; } = null!;

        /// <summary>
        /// The type of calculation to use on the shipping rate. Can only be fixed_amount for now
        /// </summary>
        [Output("type")]
        public Output<string?> Type { get; private set; } = null!;


        /// <summary>
        /// Create a ShippingRate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ShippingRate(string name, ShippingRateArgs args, CustomResourceOptions? options = null)
            : base("stripe:index/shippingRate:ShippingRate", name, args ?? new ShippingRateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ShippingRate(string name, Input<string> id, ShippingRateState? state = null, CustomResourceOptions? options = null)
            : base("stripe:index/shippingRate:ShippingRate", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ShippingRate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ShippingRate Get(string name, Input<string> id, ShippingRateState? state = null, CustomResourceOptions? options = null)
        {
            return new ShippingRate(name, id, state, options);
        }
    }

    public sealed class ShippingRateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the shipping rate can be used for new purchases. Defaults to true.
        /// </summary>
        [Input("active")]
        public Input<bool>? Active { get; set; }

        [Input("deliveryEstimates")]
        private InputList<Inputs.ShippingRateDeliveryEstimateArgs>? _deliveryEstimates;
        public InputList<Inputs.ShippingRateDeliveryEstimateArgs> DeliveryEstimates
        {
            get => _deliveryEstimates ?? (_deliveryEstimates = new InputList<Inputs.ShippingRateDeliveryEstimateArgs>());
            set => _deliveryEstimates = value;
        }

        /// <summary>
        /// The name of the shipping rate, meant to be displayable to the customer. This will appear on CheckoutSessions.
        /// </summary>
        [Input("displayName", required: true)]
        public Input<string> DisplayName { get; set; } = null!;

        /// <summary>
        /// Describes a fixed amount to charge for shipping. Must be present for now.
        /// </summary>
        [Input("fixedAmount", required: true)]
        public Input<Inputs.ShippingRateFixedAmountArgs> FixedAmount { get; set; } = null!;

        [Input("metadata")]
        private InputMap<string>? _metadata;

        /// <summary>
        /// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
        /// object in a structured format.
        /// </summary>
        public InputMap<string> Metadata
        {
            get => _metadata ?? (_metadata = new InputMap<string>());
            set => _metadata = value;
        }

        /// <summary>
        /// Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or
        /// unspecified.
        /// </summary>
        [Input("taxBehavior")]
        public Input<string>? TaxBehavior { get; set; }

        /// <summary>
        /// A tax code ID. The Shipping tax code is txcd_92010001.
        /// </summary>
        [Input("taxCode")]
        public Input<string>? TaxCode { get; set; }

        /// <summary>
        /// The type of calculation to use on the shipping rate. Can only be fixed_amount for now
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ShippingRateArgs()
        {
        }
        public static new ShippingRateArgs Empty => new ShippingRateArgs();
    }

    public sealed class ShippingRateState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the shipping rate can be used for new purchases. Defaults to true.
        /// </summary>
        [Input("active")]
        public Input<bool>? Active { get; set; }

        [Input("deliveryEstimates")]
        private InputList<Inputs.ShippingRateDeliveryEstimateGetArgs>? _deliveryEstimates;
        public InputList<Inputs.ShippingRateDeliveryEstimateGetArgs> DeliveryEstimates
        {
            get => _deliveryEstimates ?? (_deliveryEstimates = new InputList<Inputs.ShippingRateDeliveryEstimateGetArgs>());
            set => _deliveryEstimates = value;
        }

        /// <summary>
        /// The name of the shipping rate, meant to be displayable to the customer. This will appear on CheckoutSessions.
        /// </summary>
        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        /// <summary>
        /// Describes a fixed amount to charge for shipping. Must be present for now.
        /// </summary>
        [Input("fixedAmount")]
        public Input<Inputs.ShippingRateFixedAmountGetArgs>? FixedAmount { get; set; }

        /// <summary>
        /// Has the value true if the object exists in live mode or the value false if the object exists in test mode.
        /// </summary>
        [Input("livemode")]
        public Input<bool>? Livemode { get; set; }

        [Input("metadata")]
        private InputMap<string>? _metadata;

        /// <summary>
        /// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
        /// object in a structured format.
        /// </summary>
        public InputMap<string> Metadata
        {
            get => _metadata ?? (_metadata = new InputMap<string>());
            set => _metadata = value;
        }

        /// <summary>
        /// Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or
        /// unspecified.
        /// </summary>
        [Input("taxBehavior")]
        public Input<string>? TaxBehavior { get; set; }

        /// <summary>
        /// A tax code ID. The Shipping tax code is txcd_92010001.
        /// </summary>
        [Input("taxCode")]
        public Input<string>? TaxCode { get; set; }

        /// <summary>
        /// The type of calculation to use on the shipping rate. Can only be fixed_amount for now
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ShippingRateState()
        {
        }
        public static new ShippingRateState Empty => new ShippingRateState();
    }
}
