// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package stripe

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/systemfsoftware/pulumi-stripe/sdk/go/stripe/internal"
)

type WebhookEndpoint struct {
	pulumi.CustomResourceState

	// Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe
	// Version.
	ApiVersion pulumi.StringPtrOutput `pulumi:"apiVersion"`
	// Whether this endpoint should receive events from connected accounts (true), or from your account (false). Defaults to
	// false
	Connect pulumi.BoolPtrOutput `pulumi:"connect"`
	// An optional description of what the webhook is used for.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Disable the webhook endpoint if set to true.
	Disabled pulumi.BoolPtrOutput `pulumi:"disabled"`
	// The list of events to enable for this endpoint. [’*’] indicates that all events are enabled, except those that
	// require explicit selection.
	EnabledEvents pulumi.StringArrayOutput `pulumi:"enabledEvents"`
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
	// object in a structured format.
	Metadata pulumi.StringMapOutput `pulumi:"metadata"`
	// The endpoint’s secret, used to generate webhook signatures. Only returned at creation.
	Secret pulumi.StringOutput `pulumi:"secret"`
	// The URL of the webhook endpoint.
	Url pulumi.StringOutput `pulumi:"url"`
}

// NewWebhookEndpoint registers a new resource with the given unique name, arguments, and options.
func NewWebhookEndpoint(ctx *pulumi.Context,
	name string, args *WebhookEndpointArgs, opts ...pulumi.ResourceOption) (*WebhookEndpoint, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EnabledEvents == nil {
		return nil, errors.New("invalid value for required argument 'EnabledEvents'")
	}
	if args.Url == nil {
		return nil, errors.New("invalid value for required argument 'Url'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secret",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource WebhookEndpoint
	err := ctx.RegisterResource("stripe:index/webhookEndpoint:WebhookEndpoint", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetWebhookEndpoint gets an existing WebhookEndpoint resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetWebhookEndpoint(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *WebhookEndpointState, opts ...pulumi.ResourceOption) (*WebhookEndpoint, error) {
	var resource WebhookEndpoint
	err := ctx.ReadResource("stripe:index/webhookEndpoint:WebhookEndpoint", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering WebhookEndpoint resources.
type webhookEndpointState struct {
	// Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe
	// Version.
	ApiVersion *string `pulumi:"apiVersion"`
	// Whether this endpoint should receive events from connected accounts (true), or from your account (false). Defaults to
	// false
	Connect *bool `pulumi:"connect"`
	// An optional description of what the webhook is used for.
	Description *string `pulumi:"description"`
	// Disable the webhook endpoint if set to true.
	Disabled *bool `pulumi:"disabled"`
	// The list of events to enable for this endpoint. [’*’] indicates that all events are enabled, except those that
	// require explicit selection.
	EnabledEvents []string `pulumi:"enabledEvents"`
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
	// object in a structured format.
	Metadata map[string]string `pulumi:"metadata"`
	// The endpoint’s secret, used to generate webhook signatures. Only returned at creation.
	Secret *string `pulumi:"secret"`
	// The URL of the webhook endpoint.
	Url *string `pulumi:"url"`
}

type WebhookEndpointState struct {
	// Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe
	// Version.
	ApiVersion pulumi.StringPtrInput
	// Whether this endpoint should receive events from connected accounts (true), or from your account (false). Defaults to
	// false
	Connect pulumi.BoolPtrInput
	// An optional description of what the webhook is used for.
	Description pulumi.StringPtrInput
	// Disable the webhook endpoint if set to true.
	Disabled pulumi.BoolPtrInput
	// The list of events to enable for this endpoint. [’*’] indicates that all events are enabled, except those that
	// require explicit selection.
	EnabledEvents pulumi.StringArrayInput
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
	// object in a structured format.
	Metadata pulumi.StringMapInput
	// The endpoint’s secret, used to generate webhook signatures. Only returned at creation.
	Secret pulumi.StringPtrInput
	// The URL of the webhook endpoint.
	Url pulumi.StringPtrInput
}

func (WebhookEndpointState) ElementType() reflect.Type {
	return reflect.TypeOf((*webhookEndpointState)(nil)).Elem()
}

type webhookEndpointArgs struct {
	// Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe
	// Version.
	ApiVersion *string `pulumi:"apiVersion"`
	// Whether this endpoint should receive events from connected accounts (true), or from your account (false). Defaults to
	// false
	Connect *bool `pulumi:"connect"`
	// An optional description of what the webhook is used for.
	Description *string `pulumi:"description"`
	// Disable the webhook endpoint if set to true.
	Disabled *bool `pulumi:"disabled"`
	// The list of events to enable for this endpoint. [’*’] indicates that all events are enabled, except those that
	// require explicit selection.
	EnabledEvents []string `pulumi:"enabledEvents"`
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
	// object in a structured format.
	Metadata map[string]string `pulumi:"metadata"`
	// The URL of the webhook endpoint.
	Url string `pulumi:"url"`
}

// The set of arguments for constructing a WebhookEndpoint resource.
type WebhookEndpointArgs struct {
	// Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe
	// Version.
	ApiVersion pulumi.StringPtrInput
	// Whether this endpoint should receive events from connected accounts (true), or from your account (false). Defaults to
	// false
	Connect pulumi.BoolPtrInput
	// An optional description of what the webhook is used for.
	Description pulumi.StringPtrInput
	// Disable the webhook endpoint if set to true.
	Disabled pulumi.BoolPtrInput
	// The list of events to enable for this endpoint. [’*’] indicates that all events are enabled, except those that
	// require explicit selection.
	EnabledEvents pulumi.StringArrayInput
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
	// object in a structured format.
	Metadata pulumi.StringMapInput
	// The URL of the webhook endpoint.
	Url pulumi.StringInput
}

func (WebhookEndpointArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*webhookEndpointArgs)(nil)).Elem()
}

type WebhookEndpointInput interface {
	pulumi.Input

	ToWebhookEndpointOutput() WebhookEndpointOutput
	ToWebhookEndpointOutputWithContext(ctx context.Context) WebhookEndpointOutput
}

func (*WebhookEndpoint) ElementType() reflect.Type {
	return reflect.TypeOf((**WebhookEndpoint)(nil)).Elem()
}

func (i *WebhookEndpoint) ToWebhookEndpointOutput() WebhookEndpointOutput {
	return i.ToWebhookEndpointOutputWithContext(context.Background())
}

func (i *WebhookEndpoint) ToWebhookEndpointOutputWithContext(ctx context.Context) WebhookEndpointOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookEndpointOutput)
}

// WebhookEndpointArrayInput is an input type that accepts WebhookEndpointArray and WebhookEndpointArrayOutput values.
// You can construct a concrete instance of `WebhookEndpointArrayInput` via:
//
//	WebhookEndpointArray{ WebhookEndpointArgs{...} }
type WebhookEndpointArrayInput interface {
	pulumi.Input

	ToWebhookEndpointArrayOutput() WebhookEndpointArrayOutput
	ToWebhookEndpointArrayOutputWithContext(context.Context) WebhookEndpointArrayOutput
}

type WebhookEndpointArray []WebhookEndpointInput

func (WebhookEndpointArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WebhookEndpoint)(nil)).Elem()
}

func (i WebhookEndpointArray) ToWebhookEndpointArrayOutput() WebhookEndpointArrayOutput {
	return i.ToWebhookEndpointArrayOutputWithContext(context.Background())
}

func (i WebhookEndpointArray) ToWebhookEndpointArrayOutputWithContext(ctx context.Context) WebhookEndpointArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookEndpointArrayOutput)
}

// WebhookEndpointMapInput is an input type that accepts WebhookEndpointMap and WebhookEndpointMapOutput values.
// You can construct a concrete instance of `WebhookEndpointMapInput` via:
//
//	WebhookEndpointMap{ "key": WebhookEndpointArgs{...} }
type WebhookEndpointMapInput interface {
	pulumi.Input

	ToWebhookEndpointMapOutput() WebhookEndpointMapOutput
	ToWebhookEndpointMapOutputWithContext(context.Context) WebhookEndpointMapOutput
}

type WebhookEndpointMap map[string]WebhookEndpointInput

func (WebhookEndpointMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WebhookEndpoint)(nil)).Elem()
}

func (i WebhookEndpointMap) ToWebhookEndpointMapOutput() WebhookEndpointMapOutput {
	return i.ToWebhookEndpointMapOutputWithContext(context.Background())
}

func (i WebhookEndpointMap) ToWebhookEndpointMapOutputWithContext(ctx context.Context) WebhookEndpointMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebhookEndpointMapOutput)
}

type WebhookEndpointOutput struct{ *pulumi.OutputState }

func (WebhookEndpointOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WebhookEndpoint)(nil)).Elem()
}

func (o WebhookEndpointOutput) ToWebhookEndpointOutput() WebhookEndpointOutput {
	return o
}

func (o WebhookEndpointOutput) ToWebhookEndpointOutputWithContext(ctx context.Context) WebhookEndpointOutput {
	return o
}

// Events sent to this endpoint will be generated with this Stripe Version instead of your account’s default Stripe
// Version.
func (o WebhookEndpointOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebhookEndpoint) pulumi.StringPtrOutput { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

// Whether this endpoint should receive events from connected accounts (true), or from your account (false). Defaults to
// false
func (o WebhookEndpointOutput) Connect() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WebhookEndpoint) pulumi.BoolPtrOutput { return v.Connect }).(pulumi.BoolPtrOutput)
}

// An optional description of what the webhook is used for.
func (o WebhookEndpointOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WebhookEndpoint) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Disable the webhook endpoint if set to true.
func (o WebhookEndpointOutput) Disabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *WebhookEndpoint) pulumi.BoolPtrOutput { return v.Disabled }).(pulumi.BoolPtrOutput)
}

// The list of events to enable for this endpoint. [’*’] indicates that all events are enabled, except those that
// require explicit selection.
func (o WebhookEndpointOutput) EnabledEvents() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *WebhookEndpoint) pulumi.StringArrayOutput { return v.EnabledEvents }).(pulumi.StringArrayOutput)
}

// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
// object in a structured format.
func (o WebhookEndpointOutput) Metadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v *WebhookEndpoint) pulumi.StringMapOutput { return v.Metadata }).(pulumi.StringMapOutput)
}

// The endpoint’s secret, used to generate webhook signatures. Only returned at creation.
func (o WebhookEndpointOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v *WebhookEndpoint) pulumi.StringOutput { return v.Secret }).(pulumi.StringOutput)
}

// The URL of the webhook endpoint.
func (o WebhookEndpointOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *WebhookEndpoint) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

type WebhookEndpointArrayOutput struct{ *pulumi.OutputState }

func (WebhookEndpointArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*WebhookEndpoint)(nil)).Elem()
}

func (o WebhookEndpointArrayOutput) ToWebhookEndpointArrayOutput() WebhookEndpointArrayOutput {
	return o
}

func (o WebhookEndpointArrayOutput) ToWebhookEndpointArrayOutputWithContext(ctx context.Context) WebhookEndpointArrayOutput {
	return o
}

func (o WebhookEndpointArrayOutput) Index(i pulumi.IntInput) WebhookEndpointOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *WebhookEndpoint {
		return vs[0].([]*WebhookEndpoint)[vs[1].(int)]
	}).(WebhookEndpointOutput)
}

type WebhookEndpointMapOutput struct{ *pulumi.OutputState }

func (WebhookEndpointMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*WebhookEndpoint)(nil)).Elem()
}

func (o WebhookEndpointMapOutput) ToWebhookEndpointMapOutput() WebhookEndpointMapOutput {
	return o
}

func (o WebhookEndpointMapOutput) ToWebhookEndpointMapOutputWithContext(ctx context.Context) WebhookEndpointMapOutput {
	return o
}

func (o WebhookEndpointMapOutput) MapIndex(k pulumi.StringInput) WebhookEndpointOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *WebhookEndpoint {
		return vs[0].(map[string]*WebhookEndpoint)[vs[1].(string)]
	}).(WebhookEndpointOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookEndpointInput)(nil)).Elem(), &WebhookEndpoint{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookEndpointArrayInput)(nil)).Elem(), WebhookEndpointArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WebhookEndpointMapInput)(nil)).Elem(), WebhookEndpointMap{})
	pulumi.RegisterOutputType(WebhookEndpointOutput{})
	pulumi.RegisterOutputType(WebhookEndpointArrayOutput{})
	pulumi.RegisterOutputType(WebhookEndpointMapOutput{})
}
