// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class PortalConfigurationFeaturesSubscriptionCancelCancellationReason
    {
        /// <summary>
        /// Whether the feature is enabled.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Which cancellation reasons will be given as options to the customer.
        /// </summary>
        public readonly ImmutableArray<string> Options;

        [OutputConstructor]
        private PortalConfigurationFeaturesSubscriptionCancelCancellationReason(
            bool enabled,

            ImmutableArray<string> options)
        {
            Enabled = enabled;
            Options = options;
        }
    }
}
