// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Outputs
{

    [OutputType]
    public sealed class PriceTier
    {
        /// <summary>
        /// The flat billing amount for an entire tier, regardless of the number of units in the tier.
        /// </summary>
        public readonly int? FlatAmount;
        /// <summary>
        /// Same as flat_amount, but accepts a decimal value representing an integer in the minor units of the currency. Only one of flat_amount and flat_amount_decimal can be set.
        /// </summary>
        public readonly double? FlatAmountDecimal;
        /// <summary>
        /// The per unit billing amount for each individual unit for which this tier applies.
        /// </summary>
        public readonly int? UnitAmount;
        /// <summary>
        /// Same as unit_amount, but accepts a decimal value in cents with at most 12 decimal places. Only one of unit_amount and unit_amount_decimal can be set.
        /// </summary>
        public readonly double? UnitAmountDecimal;
        /// <summary>
        /// Specifies the upper bound of this tier. The lower bound of a tier is the upper bound of the previous tier adding one. Use -1 to define a fallback tier.
        /// </summary>
        public readonly int? UpTo;

        [OutputConstructor]
        private PriceTier(
            int? flatAmount,

            double? flatAmountDecimal,

            int? unitAmount,

            double? unitAmountDecimal,

            int? upTo)
        {
            FlatAmount = flatAmount;
            FlatAmountDecimal = flatAmountDecimal;
            UnitAmount = unitAmount;
            UnitAmountDecimal = unitAmountDecimal;
            UpTo = upTo;
        }
    }
}
