// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PortalConfigurationFeaturesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Information about updating the customer details in the portal.
        /// </summary>
        [Input("customerUpdate")]
        public Input<Inputs.PortalConfigurationFeaturesCustomerUpdateArgs>? CustomerUpdate { get; set; }

        /// <summary>
        /// Information about showing the billing history in the portal.
        /// </summary>
        [Input("invoiceHistory")]
        public Input<Inputs.PortalConfigurationFeaturesInvoiceHistoryArgs>? InvoiceHistory { get; set; }

        /// <summary>
        /// Information about updating payment methods in the portal.
        /// </summary>
        [Input("paymentMethodUpdate")]
        public Input<Inputs.PortalConfigurationFeaturesPaymentMethodUpdateArgs>? PaymentMethodUpdate { get; set; }

        /// <summary>
        /// Information about canceling subscriptions in the portal.
        /// </summary>
        [Input("subscriptionCancel")]
        public Input<Inputs.PortalConfigurationFeaturesSubscriptionCancelArgs>? SubscriptionCancel { get; set; }

        [Input("subscriptionUpdates")]
        private InputList<Inputs.PortalConfigurationFeaturesSubscriptionUpdateArgs>? _subscriptionUpdates;

        /// <summary>
        /// Information about updating subscriptions in the portal.
        /// </summary>
        public InputList<Inputs.PortalConfigurationFeaturesSubscriptionUpdateArgs> SubscriptionUpdates
        {
            get => _subscriptionUpdates ?? (_subscriptionUpdates = new InputList<Inputs.PortalConfigurationFeaturesSubscriptionUpdateArgs>());
            set => _subscriptionUpdates = value;
        }

        public PortalConfigurationFeaturesArgs()
        {
        }
        public static new PortalConfigurationFeaturesArgs Empty => new PortalConfigurationFeaturesArgs();
    }
}
