// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class PortalConfigurationFeaturesGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Information about updating the customer details in the portal.
        /// </summary>
        [Input("customerUpdate")]
        public Input<Inputs.PortalConfigurationFeaturesCustomerUpdateGetArgs>? CustomerUpdate { get; set; }

        /// <summary>
        /// Information about showing the billing history in the portal.
        /// </summary>
        [Input("invoiceHistory")]
        public Input<Inputs.PortalConfigurationFeaturesInvoiceHistoryGetArgs>? InvoiceHistory { get; set; }

        /// <summary>
        /// Information about updating payment methods in the portal.
        /// </summary>
        [Input("paymentMethodUpdate")]
        public Input<Inputs.PortalConfigurationFeaturesPaymentMethodUpdateGetArgs>? PaymentMethodUpdate { get; set; }

        /// <summary>
        /// Information about canceling subscriptions in the portal.
        /// </summary>
        [Input("subscriptionCancel")]
        public Input<Inputs.PortalConfigurationFeaturesSubscriptionCancelGetArgs>? SubscriptionCancel { get; set; }

        [Input("subscriptionUpdates")]
        private InputList<Inputs.PortalConfigurationFeaturesSubscriptionUpdateGetArgs>? _subscriptionUpdates;

        /// <summary>
        /// Information about updating subscriptions in the portal.
        /// </summary>
        public InputList<Inputs.PortalConfigurationFeaturesSubscriptionUpdateGetArgs> SubscriptionUpdates
        {
            get => _subscriptionUpdates ?? (_subscriptionUpdates = new InputList<Inputs.PortalConfigurationFeaturesSubscriptionUpdateGetArgs>());
            set => _subscriptionUpdates = value;
        }

        public PortalConfigurationFeaturesGetArgs()
        {
        }
        public static new PortalConfigurationFeaturesGetArgs Empty => new PortalConfigurationFeaturesGetArgs();
    }
}
