// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stripe.Inputs
{

    public sealed class ShippingRateDeliveryEstimateArgs : global::Pulumi.ResourceArgs
    {
        [Input("maximum")]
        public Input<Inputs.ShippingRateDeliveryEstimateMaximumArgs>? Maximum { get; set; }

        [Input("minimum")]
        public Input<Inputs.ShippingRateDeliveryEstimateMinimumArgs>? Minimum { get; set; }

        public ShippingRateDeliveryEstimateArgs()
        {
        }
        public static new ShippingRateDeliveryEstimateArgs Empty => new ShippingRateDeliveryEstimateArgs();
    }
}
