// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Customer extends pulumi.CustomResource {
    /**
     * Get an existing Customer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomerState, opts?: pulumi.CustomResourceOptions): Customer {
        return new Customer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stripe:index/customer:Customer';

    /**
     * Returns true if the given object is an instance of Customer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Customer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Customer.__pulumiType;
    }

    /**
     * Address map with fields related to the address: line1, line2, city, state, postalCode and country
     */
    public readonly address!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * An integer amount in cents that represents the customer’s current balance, which affect the customer’s future
     * invoices. A negative amount represents a credit that decreases the amount due on an invoice; a positive amount increases
     * the amount due on an invoice.
     */
    public readonly balance!: pulumi.Output<number | undefined>;
    /**
     * The default (auto-generated) prefix for the customer used to generate unique invoice numbers.
     */
    public /*out*/ readonly defaultInvoicePrefix!: pulumi.Output<string>;
    /**
     * An arbitrary string that you can attach to a customer object. It is displayed alongside the customer in the dashboard.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Customer’s email address. It’s displayed alongside the customer in your dashboard and can be useful for searching
     * and tracking. This may be up to 512 characters.
     */
    public readonly email!: pulumi.Output<string | undefined>;
    /**
     * The prefix for the customer used to generate unique invoice numbers. Must be 3–12 uppercase letters or numbers.
     */
    public readonly invoicePrefix!: pulumi.Output<string | undefined>;
    /**
     * Default invoice settings for this customer.
     */
    public readonly invoiceSettings!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
     * object in a structured format.
     */
    public readonly metadata!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * The customer’s full name or business name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The sequence to be used on the customer’s next invoice. Defaults to 1.
     */
    public readonly nextInvoiceSequence!: pulumi.Output<number | undefined>;
    /**
     * The customer’s phone number.
     */
    public readonly phone!: pulumi.Output<string | undefined>;
    /**
     * Customer’s preferred languages, ordered by preference.
     */
    public readonly preferredLocales!: pulumi.Output<string[] | undefined>;
    /**
     * Shipping map with fields like name, phone and fields related to the address: line1, line2, city, state, postalCode and
     * country.
     */
    public readonly shipping!: pulumi.Output<{[key: string]: string} | undefined>;

    /**
     * Create a Customer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CustomerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomerArgs | CustomerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomerState | undefined;
            resourceInputs["address"] = state ? state.address : undefined;
            resourceInputs["balance"] = state ? state.balance : undefined;
            resourceInputs["defaultInvoicePrefix"] = state ? state.defaultInvoicePrefix : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["email"] = state ? state.email : undefined;
            resourceInputs["invoicePrefix"] = state ? state.invoicePrefix : undefined;
            resourceInputs["invoiceSettings"] = state ? state.invoiceSettings : undefined;
            resourceInputs["metadata"] = state ? state.metadata : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["nextInvoiceSequence"] = state ? state.nextInvoiceSequence : undefined;
            resourceInputs["phone"] = state ? state.phone : undefined;
            resourceInputs["preferredLocales"] = state ? state.preferredLocales : undefined;
            resourceInputs["shipping"] = state ? state.shipping : undefined;
        } else {
            const args = argsOrState as CustomerArgs | undefined;
            resourceInputs["address"] = args ? args.address : undefined;
            resourceInputs["balance"] = args ? args.balance : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["email"] = args ? args.email : undefined;
            resourceInputs["invoicePrefix"] = args ? args.invoicePrefix : undefined;
            resourceInputs["invoiceSettings"] = args ? args.invoiceSettings : undefined;
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["nextInvoiceSequence"] = args ? args.nextInvoiceSequence : undefined;
            resourceInputs["phone"] = args ? args.phone : undefined;
            resourceInputs["preferredLocales"] = args ? args.preferredLocales : undefined;
            resourceInputs["shipping"] = args ? args.shipping : undefined;
            resourceInputs["defaultInvoicePrefix"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Customer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Customer resources.
 */
export interface CustomerState {
    /**
     * Address map with fields related to the address: line1, line2, city, state, postalCode and country
     */
    address?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * An integer amount in cents that represents the customer’s current balance, which affect the customer’s future
     * invoices. A negative amount represents a credit that decreases the amount due on an invoice; a positive amount increases
     * the amount due on an invoice.
     */
    balance?: pulumi.Input<number>;
    /**
     * The default (auto-generated) prefix for the customer used to generate unique invoice numbers.
     */
    defaultInvoicePrefix?: pulumi.Input<string>;
    /**
     * An arbitrary string that you can attach to a customer object. It is displayed alongside the customer in the dashboard.
     */
    description?: pulumi.Input<string>;
    /**
     * Customer’s email address. It’s displayed alongside the customer in your dashboard and can be useful for searching
     * and tracking. This may be up to 512 characters.
     */
    email?: pulumi.Input<string>;
    /**
     * The prefix for the customer used to generate unique invoice numbers. Must be 3–12 uppercase letters or numbers.
     */
    invoicePrefix?: pulumi.Input<string>;
    /**
     * Default invoice settings for this customer.
     */
    invoiceSettings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
     * object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The customer’s full name or business name.
     */
    name?: pulumi.Input<string>;
    /**
     * The sequence to be used on the customer’s next invoice. Defaults to 1.
     */
    nextInvoiceSequence?: pulumi.Input<number>;
    /**
     * The customer’s phone number.
     */
    phone?: pulumi.Input<string>;
    /**
     * Customer’s preferred languages, ordered by preference.
     */
    preferredLocales?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Shipping map with fields like name, phone and fields related to the address: line1, line2, city, state, postalCode and
     * country.
     */
    shipping?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a Customer resource.
 */
export interface CustomerArgs {
    /**
     * Address map with fields related to the address: line1, line2, city, state, postalCode and country
     */
    address?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * An integer amount in cents that represents the customer’s current balance, which affect the customer’s future
     * invoices. A negative amount represents a credit that decreases the amount due on an invoice; a positive amount increases
     * the amount due on an invoice.
     */
    balance?: pulumi.Input<number>;
    /**
     * An arbitrary string that you can attach to a customer object. It is displayed alongside the customer in the dashboard.
     */
    description?: pulumi.Input<string>;
    /**
     * Customer’s email address. It’s displayed alongside the customer in your dashboard and can be useful for searching
     * and tracking. This may be up to 512 characters.
     */
    email?: pulumi.Input<string>;
    /**
     * The prefix for the customer used to generate unique invoice numbers. Must be 3–12 uppercase letters or numbers.
     */
    invoicePrefix?: pulumi.Input<string>;
    /**
     * Default invoice settings for this customer.
     */
    invoiceSettings?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the
     * object in a structured format.
     */
    metadata?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The customer’s full name or business name.
     */
    name?: pulumi.Input<string>;
    /**
     * The sequence to be used on the customer’s next invoice. Defaults to 1.
     */
    nextInvoiceSequence?: pulumi.Input<number>;
    /**
     * The customer’s phone number.
     */
    phone?: pulumi.Input<string>;
    /**
     * Customer’s preferred languages, ordered by preference.
     */
    preferredLocales?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Shipping map with fields like name, phone and fields related to the address: line1, line2, city, state, postalCode and
     * country.
     */
    shipping?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
